spring:
  datasource:
    url: jdbc:mysql://hopper.proxy.rlwy.net:17171/railway?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: yRwQsghxnNAnuCLJBpeyJomTrcEAjRzq
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}
